remote_theme: "mmistakes/minimal-mistakes@4.22.0"
#remote_theme: minimal-mistakes-jekyll
title: VocabulariosFEMP
layout: single
plugins:
  - jekyll-include-cache  
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      
      
author:
  name   : "RPT(Relaci칩n de Puestos de Trabajo) y trabajadores municipales"
  avatar : "img/rpt.png"
  bio    : "Vocabulario para la representaci칩n de datos sobre la relaci칩n de puestos de trabajos y trabajadores municipales."
  links:
    - label: "P치gina web"
      icon: "fas fa-fw fa-link"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: ""



#remote_theme:: minimal-mistakes-jekyll
#remote_theme: mmistakes/minimal-mistakes
#remote_theme: "mmistakes/minimal-mistakes@4.22.0"
#markdown: "kramdown"
#remote_theme: minimal-mistakes-jekyll
#title: VocabulariosFEMP
#layout: simple




#sidebar:
#    - title: "Title"
 #     image: http://placehold.it/350x250
  #    image_alt: "image"
   #   text: "Some text here."
    #- title: "Another Title"
     # text: "More text here."
   #   nav: sidebar-sample

#plugins:
  #- jekyll-include-cache  
  

     


#defaults:
  # _pages
 # - scope:
  #    path: ""
   #   type: pages
  #  values:
   #   layout: single
     #   author_profile: true
